// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriemChecker.Persistence;

#nullable disable

namespace PriemChecker.Persistence.Migrations
{
    [DbContext(typeof(PriemCheckContext))]
    [Migration("20241022222024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PriemChecker.Persistence.PriemCheckResultaatEntity", b =>
                {
                    b.Property<string>("PriemKandidaatWaarde")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("AantalLoops")
                        .HasColumnType("float");

                    b.Property<bool>("IsPriemgetal")
                        .HasColumnType("bit");

                    b.Property<double?>("MilliSecondenOmTeBerekenen")
                        .HasColumnType("float");

                    b.Property<DateTime>("UitgerekendOp")
                        .HasColumnType("datetime2");

                    b.HasKey("PriemKandidaatWaarde");

                    b.ToTable("PriemCheckResultaten");
                });
#pragma warning restore 612, 618
        }
    }
}
