services:
  consolepriemchecker:
    image: consolepriemchecker
    build:
      context: .
      dockerfile: ConsolePriemChecker/Dockerfile

  webapplication1:
    image: webpriemgetal
    build:
      context: .
      dockerfile: WebPriemgetal/Dockerfile
