services:
  consoleprimetester:
    image: consoleprimetester
    build:
      context: .
      dockerfile: ConsolePrimeTester/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
