services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql  # Persistent volume for SQL Server data
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1"]
      interval: 6s
      retries: 3
    networks:
      - priemchecker-network

  consolepriemchecker:
    image: consolepriemchecker
    build:
      context: .
      dockerfile: ConsolePriemChecker/Dockerfile
    depends_on:
      - db
    networks:
      - priemchecker-network

  webpriemchecker:
    image: webpriemchecker
    build:
      context: .
      dockerfile: WebPriemChecker/Dockerfile
    depends_on:
      - db
    networks:
      - priemchecker-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=PriemCheckDb;User=sa;Password=Your_password123;
    ports:
      - "5062:80"  # Maps port 5062 on the host to port 80 in the container

  structurizr-lite:
    image: structurizr/lite
    ports:
      - "8080:8080"  # Expose Structurizr Lite on port 8080
    volumes:
      - ./structurizr:/usr/local/structurizr
    #environment:
    #  - STRUCTURIZR_WORKSPACE_PATH=/usr/local/structurizr/workspace.dsl

networks:
  priemchecker-network:
    driver: bridge
    
volumes:
  sqlserver-data:  # Persistent volume for SQL Server