services:
  consolepriemchecker:
    image: consolepriemchecker
    build:
      context: .
      dockerfile: ConsolePriemChecker/Dockerfile

  webpriemchecker:
    image: webpriemchecker
    build:
      context: .
      dockerfile: WebPriemChecker/Dockerfile
