// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriemCheckerLibrary;

#nullable disable

namespace PriemCheckerLibrary.Migrations
{
    [DbContext(typeof(PriemCheckContext))]
    [Migration("20240917225358_IdVeldInPriemCheckResultaat")]
    partial class IdVeldInPriemCheckResultaat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PriemCheckerLibrary.PriemCheckResultaat", b =>
                {
                    b.Property<int>("PriemKandidaatWaarde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriemKandidaatWaarde"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsPriemgetal")
                        .HasColumnType("bit");

                    b.HasKey("PriemKandidaatWaarde");

                    b.ToTable("PriemCheckResultaten");
                });
#pragma warning restore 612, 618
        }
    }
}
