// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriemCheckerLibrary;

#nullable disable

namespace PriemCheckerLibrary.Migrations
{
    [DbContext(typeof(PriemCheckContext))]
    partial class PriemCheckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PriemCheckerLibrary.PriemCheckResultaat", b =>
                {
                    b.Property<int>("priemKandidaatWaarde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("priemKandidaatWaarde"));

                    b.Property<bool>("isPriemgetal")
                        .HasColumnType("bit");

                    b.HasKey("priemKandidaatWaarde");

                    b.ToTable("PriemCheckResultaten");
                });
#pragma warning restore 612, 618
        }
    }
}
